#include "errcode.h"

std::map<unsigned int, std::string> CErrMsg::m_errid_msg;

CErrMsg::CErrMsg()
{
}

void CErrMsg::initErrMap()
{
	m_errid_msg[ERR_CODE_SUCCESS] = "SUCCESS";

	m_errid_msg[ERR_CODE_LOGIN_BLACKLIST]			= "ERR_LOGIN_BLACKLIST";
	m_errid_msg[ERR_CODE_LOGIN_ID_NOT_EXSIT]		= "ERR_LOGIN_ID_NOT_EXSIT";
	m_errid_msg[ERR_CODE_LOGIN_PASSWORD]			= "ERR_LOGIN_PASSWORD";
	m_errid_msg[ERR_CODE_LOGIN_VERSION_2_LOW]		= "ERR_LOGIN_VERSION_2_LOW";
	m_errid_msg[ERR_CODE_LOGIN_ID_FORMAT]			= "ERR_LOGIN_ID_FORMAT";
	m_errid_msg[ERR_CODE_LOGIN_ID_FREEZED]			= "ERR_LOGIN_ID_FREEZED";
	m_errid_msg[ERR_CODE_LOGIN_TOKEN_EXPIRE_TIME]	= "ERR_LOGIN_TOKEN_EXPIRE_TIME";
	m_errid_msg[ERR_CODE_LOGIN_NOT_FOUND_USERID]	= "ERR_LOGIN_NOT_FOUND_USERID";

	m_errid_msg[ERR_USER_IN_ROOM_BLACK_LIST]		= "ERR_USER_IN_ROOM_BLACKLIST";
	m_errid_msg[ERR_JOINROOM_PWD_WRONG]				= "ERR_JOINROOM_PASSWORD_IS_WRONG";
	m_errid_msg[ERR_FAIL_CREATE_USER]				= "ERR_CREATE_USER";
	m_errid_msg[ERR_KICKOUT_SAMEACCOUNT]			= "ERR_KICKOUT_SAMEACCOUNT";
	m_errid_msg[ERR_ROOM_IS_CLOSED]					= "ERR_ROOM_IS_CLOSED";
	m_errid_msg[ERR_ROOM_USER_IS_FULL]				= "ERR_ROOM_USER_IS_FULL";
	m_errid_msg[ERR_ROOM_KICKOUT_TIMEOUT]			= "ERR_ROOM_TIMEOUT_KICKOUT";
	m_errid_msg[ERR_ROOM_KICKOUT_AD]				= "ERR_ROOM_AD_KICKOUT";
	m_errid_msg[ERR_ROOM_SET_MIC_STATE]				= "ERR_ROOM_SET_MIC_STATE";
	m_errid_msg[ERR_NOT_ALLOW_VISIT_ON_MIC]			= "ERR_NOT_ALLOW_VISIT_ON_MIC";
	m_errid_msg[ERR_USER_NOT_ONLINE]				= "ERR_USER_NOT_ONLINE";
	m_errid_msg[ERR_USER_ON_PRIVATE_LINK]			= "ERR_USER_ON_PRIVATE_LINK";
	m_errid_msg[ERR_ROOM_SET_MIC_MODE]				= "ERR_ROOM_SET_MIC_MODE";
	m_errid_msg[ERR_USER_IS_INVITING_MIC]			= "ERR_USER_IS_INVITING_MIC";
	m_errid_msg[ERR_USER_IS_INVITED_MIC]			= "ERR_USER_IS_INVITED_MIC";
	m_errid_msg[ERR_SET_MIC_POS]					= "ERR_SET_MIC_POS";
	m_errid_msg[ERR_WAIT_MIC_IS_FULL]				= "ERR_WAIT_MIC_IS_FULL";
	m_errid_msg[ERR_WAIT_MIC_FAILED]				= "ERR_WAIT_MIC_FAILED";
	m_errid_msg[ERR_ON_PUBLIC_MIC_FAILED]			= "ERR_ON_PUBLIC_MIC_FAILED";
	m_errid_msg[ERR_DOWN_PUBLIC_MIC_FAILED]			= "ERR_DOWN_PUBLIC_MIC_FAILED";

	m_errid_msg[ERR_CODE_FAILED]					= "ERR_FAILED";
	m_errid_msg[ERR_CODE_FAILED_PACKAGEERROR]		= "ERR_PACKAGEERROR";
	m_errid_msg[ERR_CODE_FAILED_DBERROR]			= "ERR_DBERROR";
	m_errid_msg[ERR_CODE_FAILED_INVALIDCHAR]		= "ERR_INVALIDCHAR";
	m_errid_msg[ERR_CODE_FAILED_USERNOTFOUND]		= "ERR_USERNOTFOUND";
	m_errid_msg[ERR_CODE_FAILED_USERFROSEN]			= "ERR_USERFROSEN";
	m_errid_msg[ERR_CODE_FAILED_UNKNONMESSAGETYPE]	= "ERR_UNKNONMESSAGETYPE";
	m_errid_msg[ERR_CODE_FAILED_REQUEST_OUTOFRANGE]	= "ERR_REQUEST_OUTOFRANGE";
	m_errid_msg[ERR_CODE_FAILED_SAMEUSERLOGIN]		= "ERR_SAMEUSERLOGIN";
	m_errid_msg[ERR_CODE_FAILED_ROOMIDNOTFOUND]		= "ERR_ROOMIDNOTFOUND";
	m_errid_msg[ERR_CODE_FAILED_CRC]				= "ERR_CRC";
	m_errid_msg[ERR_CODE_FAILED_CREATEUSER]			= "ERR_CREATEUSER";
	m_errid_msg[ERR_CODE_FAILED_KEYWORDFOUND]		= "ERR_KEYWORDFOUND";
	m_errid_msg[ERR_CODE_FAILED_NOT_ENOUGH_GOLD]	= "ERR_NOT_ENOUGH_GOLD";
	m_errid_msg[ERR_CODE_FAILED_ALREADY_BUY]		= "ERR_ALREADY_BUY";

	m_errid_msg[ERR_CODE_FAILED_DB]					= "ERR_DB_ACTION";
	m_errid_msg[ERR_CODE_FAILED_REDIS]				= "ERR_REDIS_ACTION";
	m_errid_msg[ERR_CODE_FAILED_RPCSVR_NOTFOUND]	= "ERR_FOUND_RPCSVR";
	m_errid_msg[ERR_CODE_FAILED_RPCCALL]			= "ERR_RPCCALL";
	m_errid_msg[ERR_CODE_INVALID_PARAMETER]			= "ERR_INVALID_PARAMETER";

	m_errid_msg[ERR_CODE_MEMBER_NOT_NEED_AUTH]		= "ERR_MEMBER_NOT_NEED_AUTH";
	m_errid_msg[ERR_CODE_GROUP_INVEST_FAIL]			= "ERR_INVEST_IN_GROUP";
	m_errid_msg[ERR_CODE_GROUP_NOT_CHANGE_OWNER]	= "ERR_GROUP_NOT_CHANGE_OWNER";
	m_errid_msg[ERR_CODE_GROUP_NOTALLOW_VISIT]		= "ERR_GROUP_NOT_ALLOW_VISIT";
	m_errid_msg[ERR_CODE_JOINGROUP_NEED_MSGAUTH]	= "ERR_JOINGROUP_NEED_MSGAUTH";
	m_errid_msg[ERR_CODE_HANDLE_JOINGROUP_AUTH]		= "ERR_HANDLE_JOINGROUP_AUTH";
	m_errid_msg[ERR_CODE_JOINGROUP_APPLY_AUTH]		= "ERR_JOINGROUP_APPLY_AUTH";
	m_errid_msg[ERR_CODE_JOINGROUP_NOT_NEED_AUTH]	= "ERR_JOINGROUP_NOT_NEED_AUTH";
	m_errid_msg[ERR_CODE_JOINGROUP_NEED_VIDEOAUTH]	= "ERR_JOINGROUP_NEED_VIDEOAUTH";
	m_errid_msg[ERR_CODE_SET_GROUP_MSG_MUTE]		= "ERR_SET_USER_GROUPMSG_MUTE";
	m_errid_msg[ERR_CODE_NOT_ALLOW_JOINGROUP]		= "ERR_NOT_ALLOW_JOINGROUP";
	m_errid_msg[ERR_CODE_SET_USER_ROLETYPE]			= "ERR_SET_USER_ROLETYPE";
	m_errid_msg[ERR_CODE_USER_HAS_NO_RIGHT]			= "ERR_USER_HAS_NO_RIGHT";
	m_errid_msg[ERR_CODE_USER_QUIT_GROUP]			= "ERR_USER_QUIT_GROUP";
	m_errid_msg[ERR_CODE_KICK_USER_OUT]				= "ERR_KICK_OUT_USER";
	m_errid_msg[ERR_CODE_SET_ROOMINFO]				= "ERR_SET_ROOM_INFO";
	m_errid_msg[ERR_CODE_QRY_GROUPINFO]				= "ERR_QRY_GROUP_INFO";
	m_errid_msg[ERR_CODE_USER_JOIN_GROUP]			= "ERR_JOIN_GROUP";
	m_errid_msg[ERR_CODE_JOINGROUP_NEED_PACKET]		= "ERR_JOIN_GROUP_NEED_PACKET";

	m_errid_msg[ERR_CODE_SAMEUSER_LOGIN_OTHER_PLACE]= "ERR_SAMEUSER_LOGIN_OTHER_PLACE";
	m_errid_msg[ERR_CODE_USER_MODINFO_ERR]			= "ERR_MODIFY_USER_INFO";
	m_errid_msg[ERR_CODE_QUREY_USERGROUPINFO_ERR]	= "ERR_QUERY_USEGROUP_INFO";

	m_errid_msg[ERR_CODE_REDPACKET_EXPIRE]			= "ERR_REDPACKET_EXPIRE";
	m_errid_msg[ERR_CODE_REDPACKET_HAS_NOLEFT]		= "ERR_REDPACKET_HAS_NOLEFT";
	m_errid_msg[ERR_CODE_REDPACKET_NOT_YOURS]		= "ERR_REDPACKET_NOT_YOURS";
	m_errid_msg[ERR_CODE_REDPACKET_NOT_FOUND]		= "ERR_REDPACKET_NOT_FOUND";
	m_errid_msg[ERR_CODE_REDPACKET_HAS_TAKEN]		= "ERR_REDPACKET_HAS_TAKEN";
	m_errid_msg[ERR_CODE_REDPACKET_TAKE]			= "ERR_TAKE_REDPACKET";
	m_errid_msg[ERR_CODE_REDPACKET_CATCH]			= "ERR_CATCH_REDPACKET";
	m_errid_msg[ERR_CODE_REDPACKET_SEND]			= "ERR_SEND_REDPACKET";
	m_errid_msg[ERR_CODE_USER_NOT_IN_GROUP]			= "ERR_USER_NOT_IN_GROUP";
	m_errid_msg[ERR_CODE_REDPACKET_NOT_NEED]		= "ERR_REDPACKET_NOT_NEED";
	m_errid_msg[ERR_CODE_REDPACKET_NEED_PHOTO]		= "ERR_REDPACKET_NEED_PHOTO";
	m_errid_msg[ERR_CODE_REDPACKET_TO_SELF]			= "ERR_REDPACKET_TO_SELF";
	m_errid_msg[ERR_CODE_REDPACKET_MIN_AMOUNT_LIMIT]= "ERR_REDPACKET_MIN_AMOUNT_LIMIT";
	m_errid_msg[ERR_CODE_REDPACKET_MAX_AMOUNT_LIMIT]= "ERR_REDPACKET_MAX_AMOUNT_LIMIT";
	m_errid_msg[ERR_CODE_REDPACKET_NOT_YOURS_V2]	= "ERR_REDPACKET_NOT_YOURS";
	m_errid_msg[ERRR_CODE_REDPACKET_VISITOR_RANGE_LIMIT]	= "ERRR_REDPACKET_VISITOR_RANGE_LIMIT";

	m_errid_msg[ERR_CODE_GROUP_PRIVATE_CHAT_SWITCH_OFF]= "ERR_GROUP_PRIVATE_CHAT_SWITCH_OFF";
	m_errid_msg[ERR_CODE_GROUP_PRIVATE_CHAT_VISITOR]= "ERR_GROUP_PRIVATE_CHAT_VISITOR";
	m_errid_msg[ERR_CODE_GROUP_PRIVATE_CHAT_LIMIT]	= "ERR_GROUP_PRIVATE_CHAT_LIMIT";
	m_errid_msg[ERR_CODE_GROUP_PCHAT_IN_USER_BLACKLIST]	= "ERR_GROUP_PCHAT_IN_USER_BLACKLIST";
	m_errid_msg[ERR_CODE_DST_USER_NOT_IN_GROUP]	= "ERR_DST_USER_NOT_IN_GROUP";
	m_errid_msg[ERR_CODE_USER_NOT_VISITOR]			= "ERR_USER_NOT_VISITOR";
	m_errid_msg[ERR_CODE_GROUP_OWNER_CANNOT_QUIT]	= "ERR_GROUP_OWNER_CANNOT_QUIT";
	m_errid_msg[ERR_CODE_BELOW_MIN_GROUP_PCHAT_THRESHOLD]	= "ERR_BELOW_MIN_GROUP_PCHAT_THRESHOLD";
	m_errid_msg[ERR_CODE_RECALL_NOT_EXISTS]			= "ERR_RECALL_NOT_EXISTS";

	m_errid_msg[ERR_CODE_MAX_TREASURE_NUM_LIMIT]		= "ERR_MAX_TREASURE_NUM_LIMIT";
	m_errid_msg[ERR_CODE_BUY_TREASURE_OPENED]			= "ERR_BUY_TREASURE_OPENED";
	m_errid_msg[ERR_CODE_BUY_TREASURE_TIMEOUT]			= "ERR_BUY_TREASURE_TIMEOUT";
	m_errid_msg[ERR_CODE_BUY_TREASURE_MEMBER_ONLY]		= "ERR_BUY_TREASURE_MEMBER_ONLY";
	m_errid_msg[ERR_CODE_BUY_TREASURE_VISITOR_ONLY]		= "ERR_BUY_TREASURE_VISITOR_ONLY";
	m_errid_msg[ERR_CODE_BUY_TREASURE_DEFICIT]			= "ERR_BUY_TREASURE_DEFICIT";
	m_errid_msg[ERR_CODE_TREASURE_NOT_EXISTS]			= "ERR_TREASURE_NOT_EXISTS";
	m_errid_msg[ERR_CODE_NOT_BUY_THIS_TREASURE]			= "ERR_NOT_BUY_THIS_TREASURE";
	m_errid_msg[ERR_CODE_FORBIT_CHAT]					= "ERR_CODE_FORBIT_CHAT";
	m_errid_msg[ERR_CODE_HASE_SET_FORBIT_CHAT_SWITCH] = "ERR_CODE_HASE_SET_FORBIT_CHAT_SWITCH";
}

std::string CErrMsg::strerror(unsigned int errid)
{
	if (m_errid_msg.empty())
	{
		initErrMap();
	}

	std::map<unsigned int, std::string>::iterator iter = m_errid_msg.find(errid);
	if (iter != m_errid_msg.end())
	{
		return iter->second;
	}
	else
	{
		char cErrid[64+1] = {0};
		sprintf(cErrid, "%u", errid);
		return cErrid;
	}
}
