/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TConsumeSvrIf_CONSTANTS_H
#define TConsumeSvrIf_CONSTANTS_H

#include "TConsumeSvrIf_types.h"



class TConsumeSvrIfConstants {
 public:
  TConsumeSvrIfConstants();

};

extern const TConsumeSvrIfConstants g_TConsumeSvrIf_constants;



#endif
