// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TConsumeSvr.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class TConsumeSvrHandler : virtual public TConsumeSvrIf {
 public:
  TConsumeSvrHandler() {
    // Your initialization goes here
  }

  int32_t proc_modContributionListSwitch(const int32_t runid, const int32_t groupid, const bool Switch) {
    // Your implementation goes here
    printf("proc_modContributionListSwitch\n");
  }

  int32_t proc_modGroupGainSetting(const int32_t runid, const int32_t groupid, const bool Switch, const int8_t rangeType, const int8_t percent) {
    // Your implementation goes here
    printf("proc_modGroupGainSetting\n");
  }

  int32_t proc_modGroupUserGainSetting(const int32_t runid, const int32_t groupid, const int32_t userid, const int8_t percent) {
    // Your implementation goes here
    printf("proc_modGroupUserGainSetting\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TConsumeSvrHandler> handler(new TConsumeSvrHandler());
  shared_ptr<TProcessor> processor(new TConsumeSvrProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

