/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TUsermgrSvrIf_CONSTANTS_H
#define TUsermgrSvrIf_CONSTANTS_H

#include "TUsermgrSvrIf_types.h"



class TUsermgrSvrIfConstants {
 public:
  TUsermgrSvrIfConstants();

};

extern const TUsermgrSvrIfConstants g_TUsermgrSvrIf_constants;



#endif
