# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile C with /usr/bin/cc
# compile CXX with g++
C_FLAGS = -I/home/hezhihua/Server/trunk/httpproxysvr/. -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/lib/jsoncpp-0.10.2/include -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/pcommon/log -I/home/hezhihua/Server/trunk/httpproxysvr/deps/http-parser -I/home/hezhihua/Server/trunk/httpproxysvr/deps/multipart-parser-c -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/lib/SocketLite/src -I/home/hezhihua/Server/trunk/httpproxysvr/cmd -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/lib/libnode -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/pcommon/public -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/pcommon/thrift   

C_DEFINES = 

CXX_FLAGS = -g -Wall  -O0 -I/home/hezhihua/Server/trunk/httpproxysvr/. -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/lib/jsoncpp-0.10.2/include -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/pcommon/log -I/home/hezhihua/Server/trunk/httpproxysvr/deps/http-parser -I/home/hezhihua/Server/trunk/httpproxysvr/deps/multipart-parser-c -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/lib/SocketLite/src -I/home/hezhihua/Server/trunk/httpproxysvr/cmd -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/lib/libnode -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/pcommon/public -I/home/hezhihua/Server/trunk/httpproxysvr/../comm/pcommon/thrift   

CXX_DEFINES = 

