/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TRoomSvrIf_CONSTANTS_H
#define TRoomSvrIf_CONSTANTS_H

#include "TRoomSvrIf_types.h"



class TRoomSvrIfConstants {
 public:
  TRoomSvrIfConstants();

};

extern const TRoomSvrIfConstants g_TRoomSvrIf_constants;



#endif
