/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TPushMsgIf_CONSTANTS_H
#define TPushMsgIf_CONSTANTS_H

#include "TPushMsgIf_types.h"



class TPushMsgIfConstants {
 public:
  TPushMsgIfConstants();

};

extern const TPushMsgIfConstants g_TPushMsgIf_constants;



#endif
