/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TPushMsgIf_constants.h"



const TPushMsgIfConstants g_TPushMsgIf_constants;

TPushMsgIfConstants::TPushMsgIfConstants() {
}



