# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hezhihua/Server/trunk/httpproxysvr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hezhihua/Server/trunk/httpproxysvr/build

# Include any dependencies generated for this target.
include CMakeFiles/httpproxysvr.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/httpproxysvr.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/httpproxysvr.dir/flags.make

CMakeFiles/httpproxysvr.dir/simple_log.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/simple_log.cpp.o: ../simple_log.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/simple_log.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/simple_log.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/simple_log.cpp

CMakeFiles/httpproxysvr.dir/simple_log.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/simple_log.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/simple_log.cpp > CMakeFiles/httpproxysvr.dir/simple_log.cpp.i

CMakeFiles/httpproxysvr.dir/simple_log.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/simple_log.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/simple_log.cpp -o CMakeFiles/httpproxysvr.dir/simple_log.cpp.s

CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.requires

CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.provides: CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.provides

CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/simple_log.cpp.o

CMakeFiles/httpproxysvr.dir/http_server.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/http_server.cpp.o: ../http_server.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/http_server.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/http_server.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/http_server.cpp

CMakeFiles/httpproxysvr.dir/http_server.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/http_server.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/http_server.cpp > CMakeFiles/httpproxysvr.dir/http_server.cpp.i

CMakeFiles/httpproxysvr.dir/http_server.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/http_server.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/http_server.cpp -o CMakeFiles/httpproxysvr.dir/http_server.cpp.s

CMakeFiles/httpproxysvr.dir/http_server.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/http_server.cpp.o.requires

CMakeFiles/httpproxysvr.dir/http_server.cpp.o.provides: CMakeFiles/httpproxysvr.dir/http_server.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/http_server.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/http_server.cpp.o.provides

CMakeFiles/httpproxysvr.dir/http_server.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/http_server.cpp.o

CMakeFiles/httpproxysvr.dir/threadpool.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/threadpool.cpp.o: ../threadpool.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/threadpool.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/threadpool.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/threadpool.cpp

CMakeFiles/httpproxysvr.dir/threadpool.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/threadpool.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/threadpool.cpp > CMakeFiles/httpproxysvr.dir/threadpool.cpp.i

CMakeFiles/httpproxysvr.dir/threadpool.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/threadpool.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/threadpool.cpp -o CMakeFiles/httpproxysvr.dir/threadpool.cpp.s

CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.requires

CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.provides: CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.provides

CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/threadpool.cpp.o

CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o: ../node_watcher.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/node_watcher.cpp

CMakeFiles/httpproxysvr.dir/node_watcher.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/node_watcher.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/node_watcher.cpp > CMakeFiles/httpproxysvr.dir/node_watcher.cpp.i

CMakeFiles/httpproxysvr.dir/node_watcher.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/node_watcher.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/node_watcher.cpp -o CMakeFiles/httpproxysvr.dir/node_watcher.cpp.s

CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.requires

CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.provides: CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.provides

CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o

CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o: ../http_proxy_server.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/http_proxy_server.cpp

CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/http_proxy_server.cpp > CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.i

CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/http_proxy_server.cpp -o CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.s

CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.requires

CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.provides: CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.provides

CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o

CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o: ../sim_parser.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_6)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/sim_parser.cpp

CMakeFiles/httpproxysvr.dir/sim_parser.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/sim_parser.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/sim_parser.cpp > CMakeFiles/httpproxysvr.dir/sim_parser.cpp.i

CMakeFiles/httpproxysvr.dir/sim_parser.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/sim_parser.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/sim_parser.cpp -o CMakeFiles/httpproxysvr.dir/sim_parser.cpp.s

CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.requires

CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.provides: CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.provides

CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o

CMakeFiles/httpproxysvr.dir/http_core.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/http_core.cpp.o: ../http_core.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_7)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/http_core.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/http_core.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/http_core.cpp

CMakeFiles/httpproxysvr.dir/http_core.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/http_core.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/http_core.cpp > CMakeFiles/httpproxysvr.dir/http_core.cpp.i

CMakeFiles/httpproxysvr.dir/http_core.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/http_core.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/http_core.cpp -o CMakeFiles/httpproxysvr.dir/http_core.cpp.s

CMakeFiles/httpproxysvr.dir/http_core.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/http_core.cpp.o.requires

CMakeFiles/httpproxysvr.dir/http_core.cpp.o.provides: CMakeFiles/httpproxysvr.dir/http_core.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/http_core.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/http_core.cpp.o.provides

CMakeFiles/httpproxysvr.dir/http_core.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/http_core.cpp.o

CMakeFiles/httpproxysvr.dir/simple_config.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/simple_config.cpp.o: ../simple_config.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_8)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/simple_config.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/simple_config.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/simple_config.cpp

CMakeFiles/httpproxysvr.dir/simple_config.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/simple_config.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/simple_config.cpp > CMakeFiles/httpproxysvr.dir/simple_config.cpp.i

CMakeFiles/httpproxysvr.dir/simple_config.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/simple_config.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/simple_config.cpp -o CMakeFiles/httpproxysvr.dir/simple_config.cpp.s

CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.requires

CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.provides: CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.provides

CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/simple_config.cpp.o

CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o: ../epoll_socket.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_9)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/epoll_socket.cpp

CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/epoll_socket.cpp > CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.i

CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/epoll_socket.cpp -o CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.s

CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.requires

CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.provides: CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.provides

CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o

CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o: ../deps/multipart-parser-c/multipart_parser.c
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_10)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o"
	/usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o   -c /home/hezhihua/Server/trunk/httpproxysvr/deps/multipart-parser-c/multipart_parser.c

CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.i"
	/usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/deps/multipart-parser-c/multipart_parser.c > CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.i

CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.s"
	/usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/deps/multipart-parser-c/multipart_parser.c -o CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.s

CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.requires

CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.provides: CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.provides

CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.provides.build: CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o

CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o: ../cmd/httpest.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_11)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o -c /home/hezhihua/Server/trunk/httpproxysvr/cmd/httpest.cpp

CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/httpproxysvr/cmd/httpest.cpp > CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.i

CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/httpproxysvr/cmd/httpest.cpp -o CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.s

CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.requires

CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.provides: CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.provides

CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o: /home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_12)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o -c /home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp > CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.i

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp -o CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.s

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.requires

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.provides: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.provides

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o: /home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_13)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o -c /home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp > CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.i

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp -o CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.s

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.requires

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.provides: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.provides

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o: CMakeFiles/httpproxysvr.dir/flags.make
CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o: /home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles $(CMAKE_PROGRESS_14)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o"
	g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o -c /home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.i"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp > CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.i

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.s"
	g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp -o CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.s

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.requires:
.PHONY : CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.requires

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.provides: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.requires
	$(MAKE) -f CMakeFiles/httpproxysvr.dir/build.make CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.provides.build
.PHONY : CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.provides

CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.provides.build: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o

# Object files for target httpproxysvr
httpproxysvr_OBJECTS = \
"CMakeFiles/httpproxysvr.dir/simple_log.cpp.o" \
"CMakeFiles/httpproxysvr.dir/http_server.cpp.o" \
"CMakeFiles/httpproxysvr.dir/threadpool.cpp.o" \
"CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o" \
"CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o" \
"CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o" \
"CMakeFiles/httpproxysvr.dir/http_core.cpp.o" \
"CMakeFiles/httpproxysvr.dir/simple_config.cpp.o" \
"CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o" \
"CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o" \
"CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o" \
"CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o" \
"CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o" \
"CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o"

# External object files for target httpproxysvr
httpproxysvr_EXTERNAL_OBJECTS =

../httpproxysvr: CMakeFiles/httpproxysvr.dir/simple_log.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/http_server.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/threadpool.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/http_core.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/simple_config.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o
../httpproxysvr: CMakeFiles/httpproxysvr.dir/build.make
../httpproxysvr: CMakeFiles/httpproxysvr.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../httpproxysvr"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/httpproxysvr.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/httpproxysvr.dir/build: ../httpproxysvr
.PHONY : CMakeFiles/httpproxysvr.dir/build

CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/simple_log.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/http_server.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/threadpool.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/node_watcher.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/http_proxy_server.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/sim_parser.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/http_core.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/simple_config.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/epoll_socket.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/deps/multipart-parser-c/multipart_parser.c.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/cmd/httpest.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/syslog-nb.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CLogThread.cpp.o.requires
CMakeFiles/httpproxysvr.dir/requires: CMakeFiles/httpproxysvr.dir/home/hezhihua/Server/trunk/comm/pcommon/log/CAlarmNotify.cpp.o.requires
.PHONY : CMakeFiles/httpproxysvr.dir/requires

CMakeFiles/httpproxysvr.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/httpproxysvr.dir/cmake_clean.cmake
.PHONY : CMakeFiles/httpproxysvr.dir/clean

CMakeFiles/httpproxysvr.dir/depend:
	cd /home/hezhihua/Server/trunk/httpproxysvr/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/hezhihua/Server/trunk/httpproxysvr /home/hezhihua/Server/trunk/httpproxysvr /home/hezhihua/Server/trunk/httpproxysvr/build /home/hezhihua/Server/trunk/httpproxysvr/build /home/hezhihua/Server/trunk/httpproxysvr/build/CMakeFiles/httpproxysvr.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/httpproxysvr.dir/depend

