/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TUsermgrSvrIf_constants.h"



const TUsermgrSvrIfConstants g_TUsermgrSvrIf_constants;

TUsermgrSvrIfConstants::TUsermgrSvrIfConstants() {
}



