// This autogenerated skeleton file illustrates one way to adapt a synchronous
// interface into an asynchronous interface. You should copy it to another
// filename to avoid overwriting it and rewrite as asynchronous any functions
// that would otherwise introduce unwanted latency.

#include "TUserMsgSvr.h"
#include <thrift/protocol/TBinaryProtocol.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::async;

using boost::shared_ptr;

class TUserMsgSvrAsyncHandler : public TUserMsgSvrCobSvIf {
 public:
  TUserMsgSvrAsyncHandler() {
    syncHandler_ = std::auto_ptr<TUserMsgSvrHandler>(new TUserMsgSvrHandler);
    // Your initialization goes here
  }
  virtual ~TUserMsgSvrAsyncHandler();

  void proc_reloadUserInfo(tcxx::function<void(int32_t const& _return)> cob, const int32_t userid) {
    int32_t _return = 0;
    _return = syncHandler_->proc_reloadUserInfo(userid);
    return cob(_return);
  }

 protected:
  std::auto_ptr<TUserMsgSvrHandler> syncHandler_;
};

