
#ifndef _ERROR_CODE_HH_20160408__
#define _ERROR_CODE_HH_20160408__

#include <stdio.h>
#include <string>
#include <map>
#include <boost/thread/mutex.hpp>

enum {
	ERR_CODE_SUCCESS					= 0,	//成功
	ERR_CODE_UNKNOWN_ERROR				= 1,	//未知错误

	ERR_CODE_LOGIN_BLACKLIST			= 101,	//登陆在黑名单
	ERR_CODE_LOGIN_ID_NOT_EXSIT			= 103,	//登陆号不存在
	ERR_CODE_LOGIN_PASSWORD				= 104,	//登陆密码出错
	ERR_CODE_LOGIN_VERSION_2_LOW		= 105,	//登陆版本太低
	ERR_CODE_LOGIN_ID_FORMAT			= 106,	//登陆号格式出错
	ERR_CODE_LOGIN_ID_FREEZED			= 107,	//登陆号被冻结
	ERR_CODE_LOGIN_TOKEN_EXPIRE_TIME	= 108,	//登陆token超过有效时间
	ERR_CODE_LOGIN_NOT_FOUND_USERID		= 109,	//登陆号找不到用户ID

	ERR_USER_IN_ROOM_BLACK_LIST			= 200,	//用户在房间黑名单里
	ERR_JOINROOM_PWD_WRONG				= 201,	//房间密码不对
	ERR_FAIL_CREATE_USER				= 203,	//创建用户失败(用户名/密码失败)
	ERR_KICKOUT_SAMEACCOUNT				= 207,	//同号加入房间踢出
	ERR_ROOM_IS_CLOSED					= 405,	//房间已经关闭
	ERR_ROOM_USER_IS_FULL				= 502,	//房间人数已满
	ERR_ROOM_KICKOUT_TIMEOUT			= 522,	//超时踢出
	ERR_ROOM_KICKOUT_AD 				= 600,	//打广告踢出
	ERR_ROOM_SET_MIC_STATE				= 601,	//设置麦状态失败
	ERR_NOT_ALLOW_VISIT_ON_MIC			= 602,	//不允许游客上麦
	ERR_USER_NOT_ONLINE					= 603,	//用户不在线
	ERR_USER_ON_PRIVATE_LINK			= 604,	//用户在连麦中
	ERR_ROOM_SET_MIC_MODE				= 605,	//设置麦模式失败
	ERR_USER_IS_INVITING_MIC			= 606,	//用户在邀请连麦中
	ERR_USER_IS_INVITED_MIC				= 607,	//用户在被邀请连麦中
	ERR_SET_MIC_POS						= 608,	//用户设置麦位失败
	ERR_WAIT_MIC_IS_FULL				= 609,	//排麦人已满
	ERR_WAIT_MIC_FAILED					= 610,	//排麦失败
	ERR_ON_PUBLIC_MIC_FAILED			= 611,	//上麦失败
	ERR_DOWN_PUBLIC_MIC_FAILED			= 612,	//下麦失败
	ERR_CODE_FAILED						= 1000,	//失败 1000~1999
	ERR_CODE_FAILED_PACKAGEERROR		= 1001,	//请求包长度错误
	ERR_CODE_FAILED_DBERROR				= 1002,	//数据库类型错误 

	ERR_CODE_FAILED_INVALIDCHAR			= 1003,	//输入了非法字符
	ERR_CODE_FAILED_USERNOTFOUND		= 1004,	//找不到该用户
	ERR_CODE_FAILED_USERFROSEN			= 1005,	//用户被冻结

	ERR_CODE_FAILED_UNKNONMESSAGETYPE	= 1006,	//未知消息类型

	ERR_CODE_FAILED_REQUEST_OUTOFRANGE	= 1007,	//请求数据过多或者内容过长
	
	ERR_CODE_FAILED_SAMEUSERLOGIN		= 1008, //完全相同的用户加入房间
	ERR_CODE_FAILED_ROOMIDNOTFOUND		= 1010, //没有找到该房间
	ERR_CODE_FAILED_CRC					= 1011, //CRC校验错误
	ERR_CODE_FAILED_CREATEUSER			= 1012, //没有找到创建用户失败
	ERR_CODE_FAILED_KEYWORDFOUND		= 1013, //发现关键词
	ERR_CODE_FAILED_NOT_ENOUGH_GOLD		= 1014, //金币不足
	ERR_CODE_FAILED_ALREADY_BUY			= 1015, //已经购买
	
	ERR_CODE_FAILED_DB					= 1024,	//DB操作失败
	ERR_CODE_FAILED_REDIS				= 1025,	//Redis操作失败
	ERR_CODE_FAILED_RPCSVR_NOTFOUND		= 1026,	//RPC服务端没找到
	ERR_CODE_FAILED_RPCCALL				= 1027,	//RPC调用失败
	ERR_CODE_INVALID_PARAMETER			= 1101,	//无效的请求参数

	ERR_CODE_MEMBER_NOT_NEED_AUTH		= 1991,	//成员不需要认证
	ERR_CODE_GROUP_INVEST_FAIL			= 1992,	//发送邀请失败
	ERR_CODE_GROUP_NOT_CHANGE_OWNER		= 1993,	//群不能修改群主
	ERR_CODE_GROUP_NOTALLOW_VISIT		= 1994,	//群不允许围观
	ERR_CODE_JOINGROUP_NEED_MSGAUTH		= 1995,	//加群需要留言认证
	ERR_CODE_HANDLE_JOINGROUP_AUTH		= 1996,	//处理加群认证失败
	ERR_CODE_JOINGROUP_APPLY_AUTH		= 1997,	//申请加群认证失败
	ERR_CODE_JOINGROUP_DIFF_AUTH		= 1998,	//不是群配置里的加群认证
	ERR_CODE_JOINGROUP_NOT_NEED_AUTH	= 1999,	//加群不需要认证
	ERR_CODE_JOINGROUP_NEED_VIDEOAUTH	= 2000,	//加群需要视频认证
	ERR_CODE_SET_GROUP_MSG_MUTE			= 2001, //用户设置群消息免打扰失败
	ERR_CODE_NOT_ALLOW_JOINGROUP		= 2002,	//该群不允许加入
	ERR_CODE_SET_USER_ROLETYPE			= 2003,	//用户设置角色失败
	ERR_CODE_USER_HAS_NO_RIGHT			= 2004,	//用户没有权限
	ERR_CODE_USER_QUIT_GROUP			= 2005,	//用户退群失败
	ERR_CODE_KICK_USER_OUT				= 2006,	//踢出用户失败
	ERR_CODE_SET_ROOMINFO				= 2007,	//设置群信息失败
	ERR_CODE_QRY_GROUPINFO				= 2008,	//查询群信息失败
	ERR_CODE_USER_JOIN_GROUP			= 2009,	//用户加群失败
	ERR_CODE_JOINGROUP_NEED_PACKET		= 2010,	//加群需要发红包

	ERR_CODE_SAMEUSER_LOGIN_OTHER_PLACE	= 2011,	//同号在别的地方登陆
	ERR_CODE_USER_MODINFO_ERR			= 2012, //用户修改资料失败
	ERR_CODE_QUREY_USERGROUPINFO_ERR	= 2013,	//用户查询群信息失败

	ERR_CODE_REDPACKET_EXPIRE			= 2014,	//红包已过期
	ERR_CODE_REDPACKET_HAS_NOLEFT		= 2015,	//红包已被抢完
	ERR_CODE_REDPACKET_NOT_YOURS		= 2016,	//红包不是你的
	ERR_CODE_REDPACKET_NOT_FOUND		= 2017,	//找不到该红包
	ERR_CODE_REDPACKET_HAS_TAKEN		= 2018,	//该用户已经领过该红包
	ERR_CODE_REDPACKET_TAKE				= 2019,	//用户领取红包失败
	ERR_CODE_REDPACKET_CATCH			= 2020,	//用户抢红包失败
	ERR_CODE_REDPACKET_SEND				= 2021,	//用户发红包失败
	ERR_CODE_USER_NOT_IN_GROUP			= 2022,	//用户不属于该群
	ERR_CODE_REDPACKET_NOT_NEED			= 2023,	//不需要红包
	ERR_CODE_REDPACKET_NEED_PHOTO		= 2024,	//该红包需要用户拍照
	ERR_CODE_REDPACKET_TO_SELF			= 2025, //定向红包不能发给自己
	ERR_CODE_REDPACKET_MIN_AMOUNT_LIMIT = 2026, //每枚炮弹最小金额限制
	ERR_CODE_REDPACKET_MAX_AMOUNT_LIMIT = 2027, //每枚炮弹最大金额限制
	ERR_CODE_REDPACKET_NOT_YOURS_V2		= 2028,	//红包不属于你
	ERR_CODE_REDPACKET_FIXTIME_TOOSMALL = 2029,	//定时红包的时间小于当前时间
	ERR_CODE_REDPACKET_FIXTIME_NOT_SATRT = 2030,	//定时红包还没到开抢时间
	ERRR_CODE_REDPACKET_VISITOR_RANGE_LIMIT = 2031,	//禁止游客围观时不能发仅游客可抢的炮弹
	ERR_CODE_REDPACKET_ERR_LNG_LAT			= 2032,	//地点红包经纬度设置错误
	ERR_CODE_REDPACKET_OUTOFF_LOCATION_RANGE= 2033,	//地点红包经纬度不在领取范围
	ERR_CODE_REDPACKET_ERR_COMMAND = 2034,			//红包口令不对

	ERR_CODE_GROUP_PRIVATE_CHAT_SWITCH_OFF = 2050, //该群不允许发起私聊
	ERR_CODE_GROUP_PRIVATE_CHAT_VISITOR = 2051, //游客不允许发起群私聊
	ERR_CODE_GROUP_PRIVATE_CHAT_LIMIT	= 2052,	//未达到私聊对象亲密度门槛
	ERR_CODE_DST_USER_NOT_IN_GROUP	= 2053, //私聊对象已退出该群
	ERR_CODE_USER_NOT_VISITOR			= 2054,	//用户未围观该房间，不能发围观消息
	ERR_CODE_GROUP_OWNER_CANNOT_QUIT	= 2055,	//群主不允许退群
	ERR_CODE_BELOW_MIN_GROUP_PCHAT_THRESHOLD = 2056, //亲密度门槛小于群最小亲密度门槛
	ERR_CODE_GROUP_PCHAT_IN_USER_BLACKLIST = 2057,	//您已被对方拉黑
	ERR_CODE_RECALL_NOT_EXISTS			= 2058,	//撤回的消息不存在

	ERR_CODE_MAX_TREASURE_NUM_LIMIT		= 2061,	//群宝物数量超过限制
	ERR_CODE_BUY_TREASURE_OPENED		= 2062,	//已开奖
	ERR_CODE_BUY_TREASURE_TIMEOUT		= 2063,	//已到期
	ERR_CODE_BUY_TREASURE_MEMBER_ONLY	= 2064,	//仅成员可参与
	ERR_CODE_BUY_TREASURE_VISITOR_ONLY	= 2065,	//仅游客可参与
	ERR_CODE_BUY_TREASURE_DEFICIT		= 2066,	//宝物剩余不足
	ERR_CODE_TREASURE_NOT_EXISTS		= 2067,	//不存在该宝物
	ERR_CODE_NOT_BUY_THIS_TREASURE		= 2068,	//并未参与该宝物

	ERR_CODE_FORBIT_CHAT				= 2069,//用户已经被禁言
	ERR_CODE_HASE_SET_FORBIT_CHAT_SWITCH				= 2070,//用户已经设置过了

	ERR_CODE_GET_LUCKY_NUM				= 2071,//获取红包标识错误

	ERR_CODE_COMMENT_NEED_AUDIT=2072,//评论需要审核
	ERR_CODE_DATA_NOT_EXISTS=2073,//数据不存在
};

class CErrMsg
{
public:
	static std::string strerror(unsigned int errid);

private:
	CErrMsg();
	static void initErrMap();

private:
	static std::map<unsigned int, std::string> m_errid_msg;
};

#endif //_ERROR_CODE_HH_20160408__
