/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TChatSvrIf_CONSTANTS_H
#define TChatSvrIf_CONSTANTS_H

#include "TChatSvrIf_types.h"



class TChatSvrIfConstants {
 public:
  TChatSvrIfConstants();

};

extern const TChatSvrIfConstants g_TChatSvrIf_constants;



#endif
