/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TCommonIf_CONSTANTS_H
#define TCommonIf_CONSTANTS_H

#include "TCommonIf_types.h"



class TCommonIfConstants {
 public:
  TCommonIfConstants();

};

extern const TCommonIfConstants g_TCommonIf_constants;



#endif
