#
# Dockerfile for building MySQL images
# 
# https://github.com/addcn/docker-lnmp.git
#

FROM mysql:5.6.30
MAINTAINER lishide<376189717@qq.com>

ENV TZ "Asia/Shanghai"

# COPY config/my.cnf /etc/mysql/my.cnf
