/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TTpPushSvrIf_CONSTANTS_H
#define TTpPushSvrIf_CONSTANTS_H

#include "TTpPushSvrIf_types.h"



class TTpPushSvrIfConstants {
 public:
  TTpPushSvrIfConstants();

};

extern const TTpPushSvrIfConstants g_TTpPushSvrIf_constants;



#endif
